FROM node:6-alpine
LABEL version="1.0.0" 
ARG basedir="service-data-api"

# Node.js setup for the data-api
ENV NODE_ENV production
WORKDIR /home/app
COPY ${basedir}/ .
RUN npm install --production --silent

EXPOSE 4000
CMD npm start