GET http://localhost:4000/api/info 

###

GET http://localhost:4000/api/events

###

POST http://localhost:4000/api/events
Content-Type: application/json

{
  "title": "API injected event",
  "type": "lab",
  "start": "2010-01-01",
  "end": "2030-12-30",
  "topics": [
    { "id": 1, "desc": "Topic A" },
    { "id": 2, "desc": "Topic B" }
  ]
}

###

GET http://localhost:4000/api/events/A0nDQ

