GET http://localhost:4000/api/info 

###

GET http://localhost:4000/api/events

###

POST http://localhost:4000/api/events
Content-Type: application/json

{
  "title": "Test Demo Event",
  "type": "event",
  "start": "2018-01-09",
  "end": "2018-12-20",
  "topics": [
    { "id": 1, "desc": "Introduction" },
    { "id": 2, "desc": "Main Session" }
  ]
}

###

GET http://localhost:4000/api/events/A0nDQ

