{{- $fullName := (printf "%s-mongodb" (include "smilr.fullname" .)) -}}
{{- $name := (printf "%s-mongodb" (include "smilr.name" .)) -}}

{{ if not .Values.dataApi.mongoConnStr }}

kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ $name }}
    chart: {{ template "smilr.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: "mongo"
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ $name }}

        image: mongo:3.4-jessie

        ports:
        - containerPort: 27017

        resources:
          limits:
            memory: "500M"
            cpu: "0.25"
        
{{ if .Values.mongo.usePersistence }}
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db

  volumeClaimTemplates:
    - metadata:
        name: mongo-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: default
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 500M
{{ end }}

---

kind: Service
apiVersion: v1
metadata:
  name: "{{ template "smilr.fullname" . }}-mongodb"
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    app: "{{ $name }}"
    release: {{ .Release.Name }}

{{ end }}