#
# Azure Pipelines
# - Deploy to Kubernetes (AKS) using Helm chart
# Ben C, 2019
#
name: $(Date:yyyy-MM-dd)$(Rev:.rr)
trigger: none
pr: none

# NOTE! The 'shared-variables' variable group must be pre-created and populated
# - Expected variables: acr-connection, azure-connection
variables:
  - group: shared-variables
  - name: ingress-host
    value: 'smilr.kube.benco.io'
  - name: aks-resgrp
    value: 'demo.aks'
  - name: aks-cluster
    value: $(aks-connection)
  # - name: image-tag     # As pipeline is manual - set at deploy time
  #   value: 'latest'
  - name: acr-name
    value: $(aks-connection)

stages:
# *************************************************************************************
# Deploy stage 1 - AKS test namespace
# *************************************************************************************
- stage: deployToTest
  displayName: AKS Test

  jobs:
  - template: templates/aks-bake-deploy.yml
    parameters:
      envName: test

  - template: templates/run-postman-tests.yml
    parameters:
      dependsOn: deployToAKS
      apiHost: '$(ingress-host)/test-$(Build.BuildId)'
      frontHost: '$(ingress-host)/test-$(Build.BuildId)'

# *************************************************************************************
# Deploy stage 2 - AKS staging namespace
# *************************************************************************************
- stage: deployToStaging
  displayName: AKS Staging

  jobs:
  - template: templates/aks-bake-deploy.yml
    parameters:
      envName: staging

  - template: templates/run-loadtest.yml
    parameters:
      dependsOn: deployToAKS
      apiHost: '$(ingress-host)/staging-$(Build.BuildId)'
      frontHost: '$(ingress-host)/staging-$(Build.BuildId)'

# *************************************************************************************
# Deploy stage 3 - AKS production namespace
# *************************************************************************************
- stage: deployToProduction
  displayName: AKS Production

  jobs:
  - template: templates/aks-bake-deploy.yml
    parameters:
      envName: prod

